services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    container_name: mio-container-postgresql
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: vectordb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
